### ISSUE TITLE
BulkInsert can receive IDs out of order

### ISSUE THREAD

**Issue by pwelzien** [NorthernLight1/N.EntityFramework.Extensions#43] opened 2021-03-17 08:01 UTC
We have had a problem where the returned identity Id is sometime set out of order when using BulkInsert.

According to Microsoft's documentation, using OUTPUT does not garantee that the order is preserved.
Please see the following article:
https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15

> However, SQL Server does not guarantee the order in which rows are processed and returned by DML statements using the OUTPUT clause. It is up to the application to include an appropriate WHERE clause that can guarantee the desired semantics, or understand that when multiple rows may qualify for the DML operation, there is no guaranteed order.

This is a major problem for us, is there a way we can solve this problem?

**Comment by NorthernLight1** [comment] 2021-03-19 17:25
Pwelzien,

The library should be using an internal guid to track the entities from the client to SQL Server and back.

I will look into the code if to see how this issue is being created.

**Comment by NorthernLight1** [comment] 2021-03-19 18:49
Please re-test this bug and confirm that it has been fixed.

**Comment by NorthernLight1** [comment] 2021-03-23 20:32
Pwelzien,

I was able to replicate the issue you reported and I can confirm that the latest update fixed the issue.

**Comment by mbakervti** [comment] 2021-04-07 21:24
Is this update in v1.4.6? I have that version and I'm getting the ID values out of order. If this it going to be in 1.4.7 can you tell me when that will be available via NuGet? Thx

**Comment by NorthernLight1** [comment] 2021-04-07 21:38
The fix would have been in v1.4.6. Can you confirm that you have this version? 

I thoroughly tested v1.4.6 after fixing the issue with the ID's being out of order, and I'm confident that it has been fixed. 

I am releasing v1.4.7 today but that fixes a different issue.

**Comment by mbakervti** [comment] 2021-04-07 21:42
I'm running 1.4.6 and I have been trying to figure this out for a few hours. Related items were being assigned to the wrong things and I just realized that it's because of the IDs being out of order.

**Comment by NorthernLight1** [comment] 2021-04-08 01:31
mbakervti,

This issue will be fixed in v1.4.7 which I plan to release tomorrow.

**Comment by mbakervti** [comment] 2021-04-08 02:25
Thanks for the update. I'll test it as soon as I can get my hands on it.

**Comment by NorthernLight1** [comment] 2021-04-08 02:36
I just released v1.4.7 as a nuget package. Please test it when you have the chance and once you have confirmed that it is fixed, I will close this issue.

**Comment by mbakervti** [comment] 2021-04-08 14:11
I'm still getting the bad behavior and I'd like to send you some console dumps. Do you want them here or to a different email?

**Comment by NorthernLight1** [comment] 2021-04-08 15:16
mbakervti,

Please try v1.4.8, it should fix your issue. 

If it doesn't fix it, then you can send your dump files to this email.

**Comment by mbakervti** [comment] 2021-04-08 15:32
YES!! That appears to have it fixed. I was going to mention that it seemed to work OK with really small lists. A list of 25 worked but a list of 35 didn't. I just tried it with a list of 145 and it worked just fine.

**Comment by NorthernLight1** [comment] 2021-04-08 17:28
mbakervti,

That is great! If there is an other issues you find or any features you would like to request, please report them as a new issue.

**Closed by NorthernLight1** 2021-04-08 17:28 UTC
